// Per-page OG image generation via @vercel/og.
// SCAFFOLD ONLY — requires Vercel project config + `npm install @vercel/og`.
// Per-page HTML emitted by build.sh already references /og/<slug>.png; this
// endpoint must answer that pattern. Until enabled, Vercel will 404 the
// image URL — most crawlers fall back to no image, which is harmless.
//
// To enable:
//   1. `npm install @vercel/og` and add it to package.json
//   2. Add `"functions": { "api/og/[slug].ts": { "runtime": "edge" } }` to vercel.json
//      (or rely on `export const config = { runtime: 'edge' }` below)
//   3. Mirror the page slug → headline + group label so the image text matches
//      the page. Easiest: vendor a const map generated by build.sh.
//   4. Deploy and verify https://agentic-engineering.vercel.app/og/patterns.png
//      returns a 1200×630 PNG.

import { ImageResponse } from '@vercel/og';

export const config = {
  runtime: 'edge',
};

export default async function handler(req: Request) {
  const { searchParams, pathname } = new URL(req.url);
  // pathname looks like /og/patterns.png — strip prefix + extension.
  const match = pathname.match(/\/og\/([^/]+?)(?:\.png)?$/);
  const slug = match ? match[1] : 'index';

  // TODO: look up headline + group label from a generated map. Hardcoded fallback for now.
  const headline = searchParams.get('title') ?? 'Automate Engineering';
  const sectionLabel = searchParams.get('section') ?? 'Reference';

  return new ImageResponse(
    {
      type: 'div',
      props: {
        style: {
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          padding: '80px',
          background: '#0b0d10',
          color: '#f5f7fa',
          fontFamily: 'Inter, sans-serif',
        },
        children: [
          {
            type: 'div',
            props: {
              style: { fontSize: 28, color: '#7aa2f7', letterSpacing: '0.05em', textTransform: 'uppercase' },
              children: sectionLabel,
            },
          },
          {
            type: 'div',
            props: {
              style: { fontSize: 76, fontWeight: 800, lineHeight: 1.1 },
              children: headline,
            },
          },
          {
            type: 'div',
            props: {
              style: { fontSize: 28, color: '#9aa5b1' },
              children: 'agentic-engineering.vercel.app',
            },
          },
        ],
      },
    },
    { width: 1200, height: 630 },
  );
}
